# SQL Querying

This notebook can be used to query tables in the Congressional Data database. In order to use this notebook, you will need to set an environment variable 'CD_DWH' to the database connection string. If you do not have the credentials, please slack us at #datasci-congressdata channel and/or talk to a project lead.

**It is best practice to not hard code database URI strings directly in notebooks or code as when we push to Github, that would mean credentials are public for anyone to see.**

In [1]:
import os
import sys

import pandas as pd
pd.options.display.max_columns = 999
import sqlalchemy as sqla
from sqlalchemy import create_engine

DB_URI = os.getenv('CD_DWH')
engine = create_engine(DB_URI)

In [2]:
# Checking that the Kernel is using the Conda environment datasci-congressional-data
# Below you should see something like '/Users/Username/anaconda3/envs/datasci-congressional-data/bin/python
# If you do NOT see "datasci-congressional-data" this means you are not in the right Python Environment
# Please make sure you have gone through the onboarding docs and/or talk to a project lead.
sys.executable

'/Users/VincentLa/anaconda3/envs/datasci-congressional-data/bin/python'

Below are the tables that currently exist in the database!

In [3]:
QUERY = """
select *
from information_schema.tables
where table_schema not in ('information_schema', 'pg_catalog', 'public')
"""
with engine.begin() as conn:
    results = pd.read_sql(QUERY, conn)
results.head(100)

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,datascicongressionaldata,stg_analytics,stg_candidate_contributions,BASE TABLE,None,None,None,None,None,YES,NO,None
1,datascicongressionaldata,stg_analytics,stg_candidate_election_results,BASE TABLE,None,None,None,None,None,YES,NO,None
2,datascicongressionaldata,trg_analytics,candidate_contributions,BASE TABLE,None,None,None,None,None,YES,NO,None
3,datascicongressionaldata,data_ingest,maplight__california_candidate,BASE TABLE,None,None,None,None,None,YES,NO,None
4,datascicongressionaldata,data_ingest,maplight__california_other,BASE TABLE,None,None,None,None,None,YES,NO,None
5,datascicongressionaldata,data_ingest,casos__california_candidate_statewide_election...,BASE TABLE,None,None,None,None,None,YES,NO,None
6,datascicongressionaldata,fuzzy_merge,all_candidate_names,BASE TABLE,None,None,None,None,None,YES,NO,None
7,datascicongressionaldata,data_ingest,ceda__california_candidate_local_election_results,BASE TABLE,None,None,None,None,None,YES,NO,None
8,datascicongressionaldata,data_ingest,sfdata__campaign_finance_form460_schedulea,BASE TABLE,None,None,None,None,None,YES,NO,None

## Query Example

In [4]:
QUERY = """
select
  *
from trg_analytics.candidate_contributions
limit 10
"""
with engine.begin() as conn:
    results = pd.read_sql(QUERY, conn)
results.head(100)

,transaction_id,transaction_type,election_cycle,election,primary_general_indicator,transaction_date,transaction_amount,filed_date,recipient_committee_name,recipient_candidate_name,recipient_candidate_party,recipient_candidate_ico,recipient_candidate_status,recipient_candidate_office,recipient_candidate_district,donor_name,donor_city,donor_state,donor_zip_code,donor_employer,donor_occupation,donor_organization,donor_industry,donor_entity_type,donor_committee_id,donor_committee_name,donor_committee_type,donor_committee_party
0,773097 - A2344,Monetary Contribution,2001,2002-11-05,0,2001-06-25,100.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,"Cohen, Paul J.",Mill Valley,CA,94941,None,NOT CURRENTLY SUPPORTED,IND,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None
1,773097 - A2383,Monetary Contribution,2001,2002-11-05,0,2001-06-15,250.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,"Cohen, Phillip",Boca Raton,FL,33496,None,NOT CURRENTLY SUPPORTED,IND,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None
2,773097 - A2229,Monetary Contribution,2001,2002-11-05,0,2001-06-17,100.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,"Cole, Josephine C.",San Francisco,CA,94114,None,NOT CURRENTLY SUPPORTED,IND,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None
3,773097 - A2313,Monetary Contribution,2001,2002-11-05,0,2001-06-17,100.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,"Abrams, Donald Ira",San Francisco,CA,94131-2001,UCSF,NOT CURRENTLY SUPPORTED,IND,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None
4,773097 - A2256,Monetary Contribution,2001,2002-11-05,0,2001-06-17,200.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,"Adelman, Marcy R.",San Francisco,CA,94107,Self,NOT CURRENTLY SUPPORTED,IND,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None
5,773097 - A2257,Monetary Contribution,2001,2002-11-05,0,2001-06-15,200.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,"Adelman, Marcy R.",San Francisco,CA,94107,Self,NOT CURRENTLY SUPPORTED,IND,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None
6,773097 - A2318,Monetary Contribution,2001,2002-11-05,0,2001-06-29,3000.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,Conwest Resources Inc.,San Francisco,CA,94107,None,NOT CURRENTLY SUPPORTED,OTH,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None
7,773097 - A2219,Monetary Contribution,2001,2002-11-05,0,2001-06-18,1000.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,"Cronander, Bruce L.",San Francisco,CA,94114,None,NOT CURRENTLY SUPPORTED,IND,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None
8,773097 - A2260,Monetary Contribution,2001,2002-11-05,0,2001-06-18,50.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,"Damiani, Anna B.",San Francisco,CA,94114,State of California,NOT CURRENTLY SUPPORTED,IND,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None
9,773097 - A2325,Monetary Contribution,2001,2002-11-05,0,2001-06-15,250.0,2001-07-31,Mark Leno for Assembly 2002,"LENO, MARK",NOT CURRENTLY SUPPORTED,None,NOT CURRENTLY SUPPORTED,State Assembly,13,"Hiatt, Constance M.",San Francisco,CA,94114-3510,Hanson Bridgett & Marcus,NOT CURRENTLY SUPPORTED,IND,0,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,NOT CURRENTLY SUPPORTED,None,None

In [7]:
QUERY = """
select
  *
from data_ingest.sfdata__campaign_finance_form460_schedulea
limit 10
"""
with engine.begin() as conn:
    results = pd.read_sql(QUERY, conn)
results.head()

,filer_id,filer_naml,report_num,committee_type,rpt_date,from_date,thru_date,elect_date,tblcover_office_cd,tblcover_offic_dscr,rec_type,form_type,tran_id,entity_cd,tran_naml,tran_namf,tran_namt,tran_nams,tran_adr1,tran_adr2,tran_city,tran_state,tran_zip4,tran_emp,tran_occ,tran_self,tran_type,tran_date,tran_date1,tran_amt1,tran_amt2,tran_dscr,cmte_id,tres_naml,tres_namf,tres_namt,tres_nams,tres_adr1,tres_adr2,tres_city,tres_state,tres_zip,intr_naml,intr_namf,intr_namt,intr_nams,intr_adr1,intr_adr2,intr_city,intr_state,intr_zip4,intr_emp,intr_occ,intr_self,cand_naml,cand_namf,cand_namt,cand_nams,tbldetltran_office_cd,tbldetltran_offic_dscr,juris_cd,juris_dscr,dist_no,off_s_h_cd,bal_name,bal_num,bal_juris,sup_opp_cd,memo_code,memo_refno,bakref_tid,xref_schnm,xref_match,loan_rate,int_cmteid,tran_location,tres_location,intr_location
0,1250905,Newsom for Mayor,0,CTL,11/26/2003,10/19/2003,11/22/2003,11/04/2003,None,None,RCPT,A,A15709,OTH,"R. Zaballos & Sons, Inc.",None,None,None,None,None,Hayward,CA,94541,None,None,n,None,11/19/2003,None,$250.00,$500.00,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,n,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"94541\n(37.674148, -122.087822)",None,None
1,1317554,San Francisco Police Officers Association Issu...,0,RCP,01/27/2011,10/17/2010,12/31/2010,None,None,None,RCPT,A,INC44026,IND,Yee,Gregory,None,None,None,None,San Francisco,CA,94103,City & County of San Francisco,Police Officer,n,None,11/18/2010,None,$4.60,$163.37,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,n,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"94103\n(37.772469, -122.411853)",None,None
2,1222599,Re-Elect District 4 Supervisor Leland Yee,0,CTL,07/28/2000,01/01/2000,06/30/2000,11/07/2000,None,None,RCPT,A,A110,IND,Mah,Frank L.,None,None,None,None,San Francisco,CA,94122,Self-empl.,Consultant,n,None,06/13/2000,None,$100.00,$100.00,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,n,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"94122\n(37.761208, -122.48469)",None,None
3,1317554,San Francisco Police Officers Association Issu...,0,RCP,01/31/2012,10/23/2011,12/31/2011,None,None,None,RCPT,A,INC99151,IND,Pagano,Rene,None,None,None,None,San Francisco,CA,94103,City & County of San Francisco,Police Officer,n,None,11/22/2011,None,$1.00,$119.66,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,n,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"94103\n(37.772469, -122.411853)",None,None
4,990028,Protect our Benefits,0,RCP,07/25/2016,01/01/2016,06/30/2016,None,None,None,RCPT,A,INC3998,IND,Serpa,Anthony J,None,None,None,None,Pleasant Hill,CA,94523,None,Retired,n,None,02/09/2016,None,$200.00,$200.00,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,n,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"94523\n(37.953455, -122.074721)",None,None

In [8]:
pd.to_datetime(results.rpt_date)

0   2003-11-26
1   2011-01-27
2   2000-07-28
3   2012-01-31
4   2016-07-25
5   2005-11-01
6   2014-05-20
7   2000-07-28
8   2003-01-31
9   2002-10-04
Name: rpt_date, dtype: datetime64[ns]

In [9]:
results.tran_amt1.replace('[\$,]', '', regex=True).astype(float)

0    250.0
1      4.6
2    100.0
3      1.0
4    200.0
5    200.0
6    100.0
7    100.0
8    200.0
9    100.0
Name: tran_amt1, dtype: float64

In [10]:
results.tran_amt1

0    $250.00
1      $4.60
2    $100.00
3      $1.00
4    $200.00
5    $200.00
6    $100.00
7    $100.00
8    $200.00
9    $100.00
Name: tran_amt1, dtype: object